# Generated by Django 3.1.3 on 2021-08-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=4, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('fine_dust_10', models.IntegerField(blank=True, null=True)),
                ('min_fine_dust_2_5', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
