# Generated by Django 3.1.3 on 2021-08-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210803_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine_dust_ppm_10',
            name='grade',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine_dust_ppm_2_5',
            name='grade',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
