# Generated by Django 3.1.3 on 2021-08-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210803_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='max_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='month',
            name='min_temp',
            field=models.FloatField(),
        ),
    ]
