# Generated by Django 3.1.3 on 2021-08-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210804_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='ppm_10',
            field=models.ForeignKey(blank=True, db_column='ppm_10', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.fine_dust_ppm_10'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ppm_2_5',
            field=models.ForeignKey(blank=True, db_column='ppm_2_5', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.fine_dust_ppm_2_5'),
        ),
    ]
