# Generated by Django 3.1.3 on 2021-08-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210804_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='ppm_10',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='ppm_2_5',
        ),
    ]
